version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: base-nextjs-web
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env.local
    #    environment:
    #      - MONGODB_URI=${MONGODB_URI}
    #      - JWT_SECRET=${JWT_SECRET}
    #      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
